# Generated by Django 5.0.7 on 2024-07-29 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0004_alter_milage_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milage",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicle.car",
            ),
        ),
        migrations.AlterField(
            model_name="milage",
            name="moto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milage",
                to="vehicle.moto",
            ),
        ),
    ]
