# Generated by Django 5.0.7 on 2024-08-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0007_car_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milage",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milage",
                to="vehicle.car",
            ),
        ),
    ]
