# Generated by Django 5.0.7 on 2024-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0008_alter_milage_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="moto",
            name="amount",
            field=models.IntegerField(default=1000, verbose_name="цена"),
        ),
    ]
