# Generated by Django 5.0.7 on 2024-08-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0009_moto_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moto",
            name="amount",
        ),
    ]
