# Generated by Django 5.0.7 on 2024-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0010_remove_moto_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="цена"
            ),
        ),
        migrations.AddField(
            model_name="moto",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="цена"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="amount",
            field=models.IntegerField(
                blank=True, default=1000, null=True, verbose_name="цена"
            ),
        ),
    ]
